cluster:
  mkdir -p logs/{rule} &&
  sbatch
    --parsable
    --partition={resources.partition}
    -n {threads}
    --account=fsepru
    --mem={resources.mem_mb}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{wildcards}/%j.out
    --error=logs/{rule}/{wildcards}/%j.err
    --mail-type=ALL
    --mail-user=paul.villanueva@usda.gov
    --nodes=1
default-resources:
  - partition=short
  - mem_mb=16000
restart-times: 1
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 32
latency-wait: 60
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
conda-frontend: mamba
cluster-cancel: scancel
cluster-status: ~/.config/snakemake/slurm-status.py
