# Where to download the SRA files 
# sra_download_directory: /90daydata/fsepru/paul.villanueva/sra_scratch
sra_download_directory: output

# Where to store assembled genomes
# final_genome_directory: /90daydata/fsepru/paul.villanueva/practice_genomes
final_genome_directory: output/genomes

# Where to store final metrics
# final_metrics_directory: /90daydata/fsepru/paul.villanueva/practice_genomes/metrics
final_metrics_directory: output/metrics

# Path to the checkM2 database. Should point to the .dmnd file.
checkm2_database: /project/fsepru/paul.villanueva/databases/CheckM2_database/uniref100.KO.1.dmnd


########### Input files ############
# sra_list is a newline-separated file containing SRA accessions
# It's assumed that these are paired-end reads.
sra_list: data/sras.txt

# Short SRA lists for testing
# sra_list: data/sras_short.txt
# sra_list: data/even_shorter.txt

########### Program parameters ############
assembly:

  # Minimm contig length for SPAdes assembly
  minimum_contig_length: 200
