# Where to download the SRA files 
# sra_download_directory: /90daydata/fsepru/paul.villanueva/sra_scratch
sra_download_directory: output

# File containing SRAs to download
sra_list: data/sras.txt

# Short SRA lists for testing
# sra_list: data/even_shorter.txt
# sra_list: data/sras_short.txt

# Where to store assembled genomes
# final_genome_directory: /90daydata/fsepru/paul.villanueva/practice_genomes
final_genome_directory: output/genomes

# Where to store final metrics
# final_metrics_directory: /90daydata/fsepru/paul.villanueva/practice_genomes/metrics
final_metrics_directory: output/metrics
